### ISSUE TITLE
[Feature Request] MSAL supports Managed Identity

### ISSUE THREAD

**Issue by DidunAyodeji** [AzureAD/microsoft-authentication-library-for-java#615]
Add MSI code to MSAL from [Azure.Identity](https://github.com/Azure/azure-sdk-for-java) repo.

- [x] [Initial work with app service managed identity source](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/616)
- [x] [Add code for IMDS source](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/617)
- [x] [Add code for Azure Arc source](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/618)
- [x] [Add code for Service Fabric source](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/619) 
- [x] [Add code for cloud shell source](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/620)
- [x] [Refactor code to hide APIs not relevant to MI](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/688)
- [ ] [Integration Tests](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/689)
- [x] #695
- [x] #690
- [x] #691
- [x] #692
- [x] #693
- [x] #694

**Comment by bgavrilMS** [comment]
Done.
